public class com.crashlytics.android.core.CrashTest extends java.lang.Object
{

    public void <init>()
    {
        com.crashlytics.android.core.CrashTest $r0;

        $r0 := @this: com.crashlytics.android.core.CrashTest;

        specialinvoke $r0.<java.lang.Object: void <init>()>();

        return;
    }

    private void privateMethodThatThrowsException(java.lang.String)
    {
        com.crashlytics.android.core.CrashTest $r0;
        java.lang.String $r1;
        java.lang.RuntimeException $r2;

        $r0 := @this: com.crashlytics.android.core.CrashTest;

        $r1 := @parameter0: java.lang.String;

        $r2 = new java.lang.RuntimeException;

        specialinvoke $r2.<java.lang.RuntimeException: void <init>(java.lang.String)>($r1);

        throw $r2;
    }

    public void crashAsyncTask(long)
    {
        com.crashlytics.android.core.CrashTest $r0;
        long $l0;
        com.crashlytics.android.core.CrashTest$1 $r1;
        java.lang.Void[] $r2;

        $r0 := @this: com.crashlytics.android.core.CrashTest;

        $l0 := @parameter0: long;

        $r1 = new com.crashlytics.android.core.CrashTest$1;

        specialinvoke $r1.<com.crashlytics.android.core.CrashTest$1: void <init>(com.crashlytics.android.core.CrashTest,long)>($r0, $l0);

        $r2 = newarray (java.lang.Void)[1];

        $r2[0] = null;

        virtualinvoke $r1.<android.os.AsyncTask: android.os.AsyncTask execute(java.lang.Object[])>($r2);

        return;
    }

    public void indexOutOfBounds()
    {
        com.crashlytics.android.core.CrashTest $r0;
        int[] $r1;
        int $i0;
        io.fabric.sdk.android.Logger $r2;
        java.lang.StringBuilder $r3, $r3_1, $r3_2;
        java.lang.String $r4;

        $r0 := @this: com.crashlytics.android.core.CrashTest;

        $r1 = newarray (int)[2];

        $i0 = $r1[10];

        $r2 = staticinvoke <io.fabric.sdk.android.Fabric: io.fabric.sdk.android.Logger getLogger()>();

        $r3 = new java.lang.StringBuilder;

        specialinvoke $r3.<java.lang.StringBuilder: void <init>()>();

        $r3_1 = virtualinvoke $r3.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>("Out of bounds value: ");

        $r3_2 = virtualinvoke $r3_1.<java.lang.StringBuilder: java.lang.StringBuilder append(int)>($i0);

        $r4 = virtualinvoke $r3_2.<java.lang.StringBuilder: java.lang.String toString()>();

        interfaceinvoke $r2.<io.fabric.sdk.android.Logger: void d(java.lang.String,java.lang.String)>("CrashlyticsCore", $r4);

        return;
    }

    public int stackOverflow()
    {
        com.crashlytics.android.core.CrashTest $r0;
        int $i0, $i1, $i0_1;
        double $d0;

        $r0 := @this: com.crashlytics.android.core.CrashTest;

        $i0 = virtualinvoke $r0.<com.crashlytics.android.core.CrashTest: int stackOverflow()>();

        $d0 = staticinvoke <java.lang.Math: double random()>();

        $i1 = (int) $d0;

        $i0_1 = $i0 + $i1;

        return $i0_1;
    }

    public void throwFiveChainedExceptions()
    {
        com.crashlytics.android.core.CrashTest $r0;
        java.lang.Exception $r1, $r2, $r3, $r4;
        java.lang.RuntimeException $r5, $r5_1, $r5_2, $r5_3;

        $r0 := @this: com.crashlytics.android.core.CrashTest;

     label1:
        specialinvoke $r0.<com.crashlytics.android.core.CrashTest: void privateMethodThatThrowsException(java.lang.String)>("1");

     label2:
        return;

     label3:
        $r1 := @caughtexception;

        $r5 = new java.lang.RuntimeException;

     label4:
        specialinvoke $r5.<java.lang.RuntimeException: void <init>(java.lang.String,java.lang.Throwable)>("2", $r1);

        throw $r5;

     label5:
        $r2 := @caughtexception;

        $r5_1 = new java.lang.RuntimeException;

     label6:
        specialinvoke $r5_1.<java.lang.RuntimeException: void <init>(java.lang.String,java.lang.Throwable)>("3", $r2);

        throw $r5_1;

     label7:
        $r3 := @caughtexception;

        $r5_2 = new java.lang.RuntimeException;

     label8:
        specialinvoke $r5_2.<java.lang.RuntimeException: void <init>(java.lang.String,java.lang.Throwable)>("4", $r3);

        throw $r5_2;

     label9:
        $r4 := @caughtexception;

        $r5_3 = new java.lang.RuntimeException;

        specialinvoke $r5_3.<java.lang.RuntimeException: void <init>(java.lang.String,java.lang.Throwable)>("5", $r4);

        throw $r5_3;

        catch java.lang.Exception from label1 to label2 with label3;
        catch java.lang.Exception from label4 to label5 with label5;
        catch java.lang.Exception from label6 to label7 with label7;
        catch java.lang.Exception from label8 to label9 with label9;
    }

    public void throwRuntimeException(java.lang.String)
    {
        com.crashlytics.android.core.CrashTest $r0;
        java.lang.String $r1;
        java.lang.RuntimeException $r2;

        $r0 := @this: com.crashlytics.android.core.CrashTest;

        $r1 := @parameter0: java.lang.String;

        $r2 = new java.lang.RuntimeException;

        specialinvoke $r2.<java.lang.RuntimeException: void <init>(java.lang.String)>($r1);

        throw $r2;
    }
}
