class io.fabric.sdk.android.services.concurrency.AsyncTask$3 extends java.util.concurrent.FutureTask
{
    final io.fabric.sdk.android.services.concurrency.AsyncTask this$0;

    void <init>(io.fabric.sdk.android.services.concurrency.AsyncTask, java.util.concurrent.Callable)
    {
        io.fabric.sdk.android.services.concurrency.AsyncTask$3 $r0;
        io.fabric.sdk.android.services.concurrency.AsyncTask $r1;
        java.util.concurrent.Callable $r2;

        $r0 := @this: io.fabric.sdk.android.services.concurrency.AsyncTask$3;

        $r1 := @parameter0: io.fabric.sdk.android.services.concurrency.AsyncTask;

        $r2 := @parameter1: java.util.concurrent.Callable;

        $r0.<io.fabric.sdk.android.services.concurrency.AsyncTask$3: io.fabric.sdk.android.services.concurrency.AsyncTask this$0> = $r1;

        specialinvoke $r0.<java.util.concurrent.FutureTask: void <init>(java.util.concurrent.Callable)>($r2);

        return;
    }

    protected void done()
    {
        io.fabric.sdk.android.services.concurrency.AsyncTask$3 $r0;
        java.lang.InterruptedException $r1;
        java.util.concurrent.ExecutionException $r2;
        java.lang.RuntimeException $r3;
        java.util.concurrent.CancellationException $r4;
        io.fabric.sdk.android.services.concurrency.AsyncTask $r5, $r5_1;
        java.lang.Object $r6;
        java.lang.Throwable $r7;

        $r0 := @this: io.fabric.sdk.android.services.concurrency.AsyncTask$3;

        $r5 = $r0.<io.fabric.sdk.android.services.concurrency.AsyncTask$3: io.fabric.sdk.android.services.concurrency.AsyncTask this$0>;

     label1:
        $r6 = virtualinvoke $r0.<io.fabric.sdk.android.services.concurrency.AsyncTask$3: java.lang.Object get()>();

        staticinvoke <io.fabric.sdk.android.services.concurrency.AsyncTask: void access$400(io.fabric.sdk.android.services.concurrency.AsyncTask,java.lang.Object)>($r5, $r6);

     label2:
        return;

     label3:
        $r1 := @caughtexception;

        staticinvoke <android.util.Log: int w(java.lang.String,java.lang.Throwable)>("AsyncTask", $r1);

        return;

     label4:
        $r2 := @caughtexception;

        $r3 = new java.lang.RuntimeException;

        $r7 = virtualinvoke $r2.<java.util.concurrent.ExecutionException: java.lang.Throwable getCause()>();

        specialinvoke $r3.<java.lang.RuntimeException: void <init>(java.lang.String,java.lang.Throwable)>("An error occured while executing doInBackground()", $r7);

        throw $r3;

     label5:
        $r4 := @caughtexception;

        $r5_1 = $r0.<io.fabric.sdk.android.services.concurrency.AsyncTask$3: io.fabric.sdk.android.services.concurrency.AsyncTask this$0>;

        staticinvoke <io.fabric.sdk.android.services.concurrency.AsyncTask: void access$400(io.fabric.sdk.android.services.concurrency.AsyncTask,java.lang.Object)>($r5_1, null);

        return;

        catch java.lang.InterruptedException from label1 to label2 with label3;
        catch java.util.concurrent.ExecutionException from label1 to label2 with label4;
        catch java.util.concurrent.CancellationException from label1 to label2 with label5;
    }
}
